### ISSUE TITLE
New Obsidian update breaks functionality

### ISSUE THREAD

**Issue by Hautemeal** [pyrochlore/obsidian-tracker#102]
I just updated to the newest version of Obsidian (v0.13.14) and all my tracker pages are returning "Error parsing YAML".

Here's some examples of code I'm using that result in this issue:

```
searchType: frontmatter
searchTarget: anxiety
folder: 20 Daily Notes
startDate: -1w
datasetName: anxiety
line:
    title: Week
    yAxisLabel: Peak Anxiety
    yAxisUnit:
    lineColor: teal
	yMin: 0
    yMax: 10
	xAxisTickLabelFormat: ddd
	showLegend: false
	legendPosition: right
	legendBgColor: white
	lineWidth: 5
	pointColor: white
```
```
searchType: tag
searchTarget: mood/happy, mood/anxious, mood/high, mood/distracted, mood/accomplished, mood/excited, mood/frustrated, mood/nervous, mood/vibin
pie:
    title: Mood Pie
	data: '{{sum(dataset(0))}},{{sum(dataset(1))}},{{sum(dataset(2))}},{{sum(dataset(3))}},{{sum(dataset(4))}},{{sum(dataset(5))}},{{sum(dataset(6))}},{{sum(dataset(7))}},{{sum(dataset(8))}}'
	dataColor: 'green,red,blue,purple,teal,grey,orange,salmon,pink'
	label: Happy, Anxious, Chill, Distracted, Accomplished, Excited, Frustrated, Nervous, Vibin
	ratioInnerRadius: 0.5
```

I'm not very code-savvy, so I'm not really sure where to begin with diagnosing and resolving this issue myself. I don't use many add-ons, but the few I do use are up to date. Thanks in advance!
