### ISSUE TITLE
Sleep tracker with 3 values

### ISSUE THREAD

**Issue by foenixp** [pyrochlore/obsidian-tracker#182]
Hi,
I wonder if it's possible to create a chart with 3 values on it, ideally 2 y-axis.
 I want to track both my sleep & wake up time, as well as the hours that i slept in one single chart. Right now I am able to make a chart with sleep and wake up time, is there a way to incorporate the slept hours in it? 
My code is:
 ```
searchType: dvField
searchTarget: sleep[0], sleep[1]
startDate: 2023-01-02 Monday
endDate: 2023-01-08 Sunday
folder: "folder"
fixedScale: 1.2
fitPanelWidth: false
valueShift: -24:00, 0
shiftOnlyValueLargerThan: 12:00, 0
datasetName: Sleep, WakeUp
line:
    title: "Sleep"
    yAxisLabel: "Time (24h)"
    lineColor: yellow, pink
    showPoint: true
    showLegend: true
    yMax: 12:00
    yMin: -06:00
```

My inline dataview keys and value are:
- sleep:: 2:00 am/11:00 am
- sleeptime:: 9

I want to incorporate the sleeptime into the chart.
![image](https://user-images.githubusercontent.com/102443314/210827986-45cb97c8-e3be-4d44-95a8-2ba01d7c4dee.png)
