### ISSUE TITLE
Labels and lines not showing

### ISSUE THREAD

**Issue by dcoales** [pyrochlore/obsidian-tracker#19]
I have the following set up:

``` tracker
searchType: text
searchTarget: 'Run::.*@(?<value>[\s]*[0-9]+[\.][0-9]*)'
folder: /journals
startDate: 2021 05 01, Sat
line:
    title: Running Pace
    xAxisLabel: When
    yAxisLabel: Pace
	yAxisUnit: min/km
	lineColor: red
```

However, none of the labels show nor any lines.  I just get this:

<img width="179" alt="tracker" src="https://user-images.githubusercontent.com/19651447/118530130-34ff4f00-b73c-11eb-95e9-1f4e1d5752d2.png">

I can't figure out what I'm doing wrong !

**Comment by pyrochlore** [comment]
Could you provide me some example data to do some tests?
Those pieces of data in your diary to track.

**Comment by pyrochlore** [comment]
You can also send a direct message to me on discord Obsidian Member Group if you want.

**Comment by pyrochlore** [comment]
[Here](https://drive.google.com/file/d/1SmjGsA1QgAdFkZEXFSBKWyHCl_tG38D5/view?usp=sharing) is a zip file containing the test files working on my side.
Please have a look of it.

**Comment by dcoales** [comment]
Using your zip file I see the following:

![image](https://user-images.githubusercontent.com/19651447/118959411-360dc780-b95a-11eb-929a-46c6f522a533.png)

I've attached a zip file of my own which produces the following - it misses some dates:
![image](https://user-images.githubusercontent.com/19651447/118959665-71a89180-b95a-11eb-8f96-1764a7c48cfe.png)

I don't get labels in either case although your sample does produce the red line at least.  No idea why it doesn't in my journals folder.
[Test.zip](https://github.com/pyrochlore/obsidian-tracker/files/6514910/Test.zip)

**Comment by pyrochlore** [comment]
![image](https://user-images.githubusercontent.com/3617615/118968195-316b0280-b99e-11eb-9a9d-aa3330c90c8c.png)
Please check the format of your daily notes.
There are two spaces between 05 and 17, also between 05 and 19.
That should be the reason why the plugin cannot use the specified dateFormat to parse them.

**Comment by dcoales** [comment]
Thanks, I'm an idiot :-)

I've fixed the dates and the chart now looks like:
![image](https://user-images.githubusercontent.com/19651447/118980419-5f861d80-b971-11eb-92f4-737a76154905.png)
It appears that it won't draw the line between dots if there is a gap.  So there is no line between the 17th and 18th.  Is there something I can do about that ?  I don't run every day so there will always be gaps.

Also I still can't get the labels to appear.

Thanks for your help.

**Comment by pyrochlore** [comment]
The missing line was caused by the missing point at 2021/05/18.
By default, the plugin will not connect points cross missing points for you.
To connect them, please add a parameter 'fillGap: true' at the YAML root.

I am not sure why the labels are missing.
The labels showed here even with the unmodified sample you provided.

**Comment by dcoales** [comment]
That's excellent thank you.  I've tried adding the fillGap: true line to the YAML but it's having no effect.  I may be putting it in the wrong place.  I've tried in the YAML at the top of the page i.e. my file looks like:
```
---
fillGap: true
---

``` tracker
searchType: text
searchTarget: 'Run::.*@(?<value>[\s]*[0-9]+[\.][0-9]*)'
folder: /Test
startDate: 2021 05 17, Mon
dateFormat: 'YYYY MM DD, ddd'
line:
    title: Running Pace
    xAxisLabel: When
    yAxisLabel: Pace
    yAxisUnit: min/km
    lineColor: red
```

I've upgraded and am using 1.5.0

**Comment by pyrochlore** [comment]
Please try this

``` tracker
searchType: text
searchTarget: 'Run::.*@(?<value>[\s]*[0-9]+[\.][0-9]*)'
folder: /Test
startDate: 2021 05 17, Mon
dateFormat: 'YYYY MM DD, ddd'
line:
    title: Running Pace
    xAxisLabel: When
    yAxisLabel: Pace
    yAxisUnit: min/km
    lineColor: red
    fillGap: true
```
```

**Comment by dcoales** [comment]
Perfect thank you.  I did try it in the tracker block but at the same level as the dateFormat and that just through an error.
All good now though.

Thanks again.

**Comment by pyrochlore** [comment]
By the way, in version 1.5.0.
You can try this
``` tracker
searchType: dvField
searchTarget: Run
startDate: 2021 05 17, Mon
dateFormat: 'YYYY MM DD, ddd'
line:
    title: Running Pace
    xAxisLabel: When
    yAxisLabel: Pace
    yAxisUnit: min/km
    lineColor: red
    fillGap: true
```

**Comment by dcoales** [comment]
Wow fantastic.  Is it possible to have two yAxis labels - one is the distance the other is the pace ?  I know, I know, some people are never satisfied.

**Comment by pyrochlore** [comment]
Yes, you already have it.
It works like this
```
searchType: dvField
searchTarget: Run[0], Run[1]
startDate: 2021 05 17, Mon
dateFormat: 'YYYY MM DD, ddd'
separator: '@'
line:
    title: Running Pace
    xAxisLabel: When
    yAxisLabel: Distance, Pace
    yAxisUnit: km, min/km
    lineColor: red, yellow
    fillGap: true
```
