### ISSUE TITLE
Is it possible to set the bar width for each interval?

### ISSUE THREAD

**Issue by knyghtLyght** [pyrochlore/obsidian-tracker#194]
My bars look very thin

![image](https://user-images.githubusercontent.com/12706138/213288236-413b2cde-5c4c-4974-92bf-64892c0334f8.png)

```
searchType: dvField
searchTarget: Fat Mass, Lean Mass
folder: Health/Styku
datasetName: Fat Mass, Lean Mass
startDate: 2022-09-01
endDate: 2023-02-01
bar:
    title: Mass Tracking
    barColor: yellow, red
    yAxisLabel: Mass
    yAxisUnit: lb
    yMin: 0
    showLegend: True
```
