### ISSUE TITLE
[BUG] textValueMap parsing emoticons shows "No valid Y values found in note"

### ISSUE THREAD

**Issue by OmniNaut** [pyrochlore/obsidian-tracker#237]
Trying to map emojis against numbers to put in a line graph, but no matter what I try emojis as original value always shows "No valid Y values found in note". If i change the original value to text or number textValueMap works fine.
I use inline metadata. I tried to change to frontmatter but the bug still exists.
I used this example. https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestTextValueMap.md

This is the code I used:

```
searchType: dvfield
searchTarget: Physical, Mental, Emotional, Spiritual, Creative, Peaceful
folder: Tracking/Daily
startDate: 2023-06-05
endDate: 2023-06-11
textValueMap:
	😂: 6
	🙂: 5  
	😐: 4
	☹️: 3
	😞: 2
	😭: 1
datasetName: 🚹 Physical, 🧠 Mental, 😶 Emotional, ☮️ Spiritual, 🎨 Creative, ✌🏼 Peaceful
fixedScale: 1.25
margin: 2
line:
    lineColor: yellow, orange, lightblue, red, pink, green
    lineWidth: 3
    showLegend: true
    legendPosition: right
```

Unfortunately since the developers hasn't be active for over a year, I consider this plugin abandoned. So maybe there is a work around  we as a community can come up with. At least it's a documentation of the issue.

Plugin version: 1.10.9
Obsidian: 1.4.2 (Insider)
Windows 11 22H2
