### ISSUE TITLE
How to display y axis as integer?

### ISSUE THREAD

**Issue by aaronjylee92** [pyrochlore/obsidian-tracker#264]
I can't seem to find a parameter to be able to change the y-axis to an integer value.

```
``` tracker
searchType: text
searchTarget: 🍅
startDate: 2023-11-23
folder: /Daily Notes
line:
    title: "Pomodoro Tracker"
    lineColor: red
    xAxisLabel: Date
    yAxisLabel: Amount
		yAxisTickInterval: 1
		yMin: 0
		
```
```


<img width="438" alt="image" src="https://github.com/pyrochlore/obsidian-tracker/assets/150339936/4bd5cc0b-dff1-4de5-b7d1-372f18bfb86c">
