### ISSUE TITLE
fitPanelWidth Questions

### ISSUE THREAD

**Issue by pppaapp** [pyrochlore/obsidian-tracker#271]
![1111111111](https://github.com/pyrochlore/obsidian-tracker/assets/31263588/02ed09cf-4a4c-40d6-9544-d2fb8d9ad034)

I enabled fitPanelWidth

On macOS there is no space, but on Windows there is a space to the right

Is there a way to get rid of space like macOS?

```
searchType: task.done
searchTarget: 'test'
datasetName: 영양제
fitPanelWidth: true
month:
	mode: annotation
	annotation: 💊
	startWeekOn: "mon"
	color: tomato
	headerMonthColor: orange
	todayRingColor: orange
	selectedRingColor: steelblue
	showSelectedValue: false
	dimNotInMonth: false
	showAnnotationOfAllTargets: true
```

```css
.right-block-tracker {
    --metadata-display-reading: none;
    overflow: hidden !important;
    padding: 10px 2px 10px 10px;
}
```
