### ISSUE TITLE
Syntax for checkboxes in frontmatter?

### ISSUE THREAD

**Issue by TechLifeWeb** [pyrochlore/obsidian-tracker#291]
Apologies if this has been posted but I looked around and didn't see it. I'm using version 1.13.1.

I see that checkboxes in frontmatter is supported now but how do you use it?
Trying to track a frontmatter check box called read. This code doesn't work. It does add up all the days I've had the item in my frontmatter but doesn't consider if the value is true or false.

```
searchType: frontmatter
searchTarget: read
folder: Daily
startDate: 2023-12-30
summary:
     template: "Reading - Longest Streak: {{maxStreak()}} day(s) | Current streak: {{currentStreak()}} day(s)"
     style: "font-size:small;"
```

I have seen people suggest the following and I guess it works but I wasn't sure that was the official way
```
searchType: text
searchTarget: 'read: true'
```
