### ISSUE TITLE
Unable to get the plugin to work.

### ISSUE THREAD

**Issue by linkpy** [pyrochlore/obsidian-tracker#30]
We are trying to use Tracker to make some graph related to helpdesk agent performances.

We have a collection of notes, each one of them is a review of an incident created by an agent, and has the following frontmatter :

```yaml
agent: a_name
incident: a_string
sysid: another_string
incident creation date: 2021-06-21T06:13:56
```
Note: the note's name is the incident string (thus not a date).

After looking for a while on the doc, we were unable to get that graph to work :
```yaml
searchType: frontmatter, frontmatter
searchTarget: incident creation date, agent
datasetName: xDataset, agentDataset
folder: Analysis/Incidents
bar:
    title: "Bar Chart"
    xAxisLabel: Date
    yAxisLabel: Count
```

Over and over again we have "No notes found under the given search condition".
They are notes in the given folder. Each of them have the right frontmatter (they are generated by a script) so we don't know what we are doing wrong.
Could you help us?
