### ISSUE TITLE
How to specify legend labels for tags?

### ISSUE THREAD

**Issue by Rhydderch** [pyrochlore/obsidian-tracker#31]
Hello,

How can I specify the name of the labels for the legend?
It would be nice if by default it would use the name of the tags.
But is it possible to set the names manually?
(I went through the docs and the example but couldn't find what I needed)

Here is my code
````
```tracker
searchType: tag
searchTarget: time-tracking/phd, time-tracking/crypto, time-tracking/social, time-tracking/sport
folder: /02_AREAS/daily_notes
startDate: 2021-06-21_Mon
endDate: 2021-06-27_Sun
bar:
    title: Time tracking for week 24
	yAxisLabel: Time
    yAxisUnit: h
    yMin: 0
	yMax: 16
	allowInspectData: true
	showLegend: true
	legendPosition: right
    barColor: green, yellow, blue, orange
```
````

Here is what I get:
![image](https://user-images.githubusercontent.com/3197629/123644153-65e79f00-d825-11eb-9eaa-3ce5ade676fc.png)

Thank you for this awesome plugin. It helps me keep things in Obsidian.
