### ISSUE TITLE
Feature request: line chart should support the y-axis for durations greater than 24 hours

### ISSUE THREAD

**Issue by paulequilibrio** [pyrochlore/obsidian-tracker#386]
No line chart is rendered when `yMax` is set to a value greater than `24:00`.

## Expected Behavior

The line chart should support the y-axis for durations greater than 24 hours.

## Current Behavior

No chart is rendered, just display the error message "Invalid inputs for yMax"

## Context

I'm using a simple line chart for my fasts
```
searchType: frontmatter
searchTarget: fast_duration
datasetName: Fast
folder: daily
line:
    yAxisLabel: Hours
    yMin: 08:00
    yMax: 24:00
    yAxisTickInterval: 01:00
    xAxisLabel: Day
``` 
This week I managed to fast for more than 24 hours, but when I tried to update the `yMax` to `50:00` I got the message "Invalid inputs for yMax"
