### ISSUE TITLE
searchType: table fails with error in console

### ISSUE THREAD

**Issue by davecahill** [pyrochlore/obsidian-tracker#40]
This could easily be a syntax mistake on my part, but providing details in case it's not.

Table is in `/testTable.md`, contents:
```
# Hello

| theDate    | theValue | 
| ---------- | -------- |
| 2021-07-11 | 2        |
| 2021-07-12 | 4        |
| 2021-07-20 | 10       |

```

Tracker is in `/testTracker.md`, contents:
````
```tracker
searchType: table
searchTarget: testTable[0][0], testTable[0][1]
xDataset: 0
line:
    yAxisLocation: none, left
    lineColor: none, red
    showLegend: true
```
````

This gives the following error in console when viewing `testTracker.md`:
```
main.ts:469 Uncaught (in promise) TypeError: Cannot read property 'getParentTarget' of null
    at _l.eval (eval at <anonymous> (app.js:1), <anonymous>:15:167456)
    at Generator.next (<anonymous>)
    at o (eval at <anonymous> (app.js:1), <anonymous>:15:165)
```

I'm using Obsidian v0.12.10 and Tracker v1.8.2.
