### ISSUE TITLE
Chart showing frequency of values

### ISSUE THREAD

**Issue by solpyro** [pyrochlore/obsidian-tracker#410]
I have the frontmatter field `mood: 🙂` in my daily entries, and I want to build a pie chart to show the frequency of each emoji (or any unique string really). 

My current attempt is
```
searchType: frontmatter
searchTarget: mood
dataset: mood
pie:
    label: mood
    data: mood
```
which renders the error `No valid Y value found in notes`. I'm sure I need to do some processing on the data to group and count the unique values, but I can't find how to do that in the examples and documentation.
