### ISSUE TITLE
Feature request: Trackable List Value in Frontmatter

### ISSUE THREAD

**Issue by edlime** [pyrochlore/obsidian-tracker#420]
I'd like to track fruits I consumed from a list in Frontmatter and to target a specific value.

I've implemented using `searchType: text` value as follows:

```
searchType: text
searchTarget: apple
folder: journal/2024/01
datasetName: January
startDate: 2024-01-01
endDate: 2024-01-31
month:
    startWeekOn: Mon
```

but this messes up the tracking when I mentioned `apple` in the body of my journal despite not consuming an apple for the day. So I was thinking of putting `fruits` as part of Frontmatter.

```
---
fruits:
  - "[[apple]]"
  - "[[orange]]"
  - "[[banana]]"
---
```

However, I didn't see how this would work based on the [documentation](https://github.com/pyrochlore/obsidian-tracker/blob/master/docs/InputParameters.md).

## Possible Solution

If possible, I'd like to propose adding another parameter:

```
searchType: frontmatter
searchTarget: fruits
searchTargetValue: apple
folder: journal/2024/01
datasetName: January
startDate: 2024-01-01
endDate: 2024-01-31
month:
    startWeekOn: Mon
```

Then I'd be able to display my streaks using the target values that have internal links in `List` type properties.

**Comment by edlime** [comment]
Thanks a lot @curious-archaea! Is it possible to have internal linking? say `habits: "[[yoga]]"` wherein it links to `yoga.md` and from 

```yaml
searchType: frontmatterlist
searchTarget: habits[yoga]
folder: diary
startDate: 2026-02-01
endDate: 2026-02-28
datasetName: Yoga
month:
	color: lightblue
```
