### ISSUE TITLE
Seeing "null" in calendar mode

### ISSUE THREAD

**Issue by alexzavalny** [pyrochlore/obsidian-tracker#460]
Looks like this for me:

```tracker
searchType: dvField
searchTarget: mood
datasetName: Mood
month:
    mode: annotation
    color: green
	circleColorByValue: true
	todayRingColor: red
	selectedRingColor: red
```

in my note it is just 

mood::3

<img width="681" alt="Image" src="https://github.com/user-attachments/assets/bc76032e-ecba-457b-88f8-216f73e2b13e" />

**Comment by Lokesh-Bharath** [comment]
Hey Alex, you are seeing this issue because you used 
**mode: annotation**

but you are missing a key 
**annotation:** 
i.e. did not specify what you need the data to be annotated with.

```
searchType: dvField
searchTarget: mood
datasetName: Mood
month:
    mode: annotation
    annotation: 🧘‍♂️
    color: green
    circleColorByValue: true
    todayRingColor: red
    selectedRingColor: red
```

You can fix the issue adding the key as specified above.

Refer to https://github.com/pyrochlore/obsidian-tracker/blob/master/examples/TestCalendar.md and https://github.com/pyrochlore/obsidian-tracker/blob/master/docs/InputParameters.md for more information on other keys.
