### ISSUE TITLE
Displaying a value in the "month" mode depending on frontmatter

### ISSUE THREAD

**Issue by lakicsv** [pyrochlore/obsidian-tracker#463]
Hello,

I am not sure if this is an issue (with me, not finding it in the doc) or a feature request... :-)

I am trying to track /view the occurence of 2 different values which represent one searchTarget. As an example: 

 searchTarget : alcohol which can have 2 values, wine or beer (or missing / none). I want to display them on a calendar by different colors, let's say green for beer, red for wine. how can i do this? 

Thanks: Viktor

**Comment by ProHaller** [comment]
Hey @lakicsv a bit late, but I had the same issue. 
There doesn't seem to be a straightforward way to do it for now. 
However, I found these two workarounds: 

## Map the values to a gradient and show circles:

```yaml
searchType: frontmatter
searchTarget: alcohol
datasetName: Alcohol
textValueMap: 
	beer: 3
	wine: 5
month:
	yMin: 0
	yMax: 5
    circleColorByValue: true
	showSelectedValue: true
	color: purple
```
<img width="360" height="320" alt="Image" src="https://github.com/user-attachments/assets/58018600-142e-4a4f-890e-01ecd9c45c07" />

## Double the datasets and map an annotation to different thresholds:

```yaml
searchType: frontmatter
searchTarget: alcohol, alcohol
datasetName: Wine, Beer
endDate: 2026-01-31
textValueMap:
    beer: 3
	wine: 5
month:
    mode: annotation
    showAnnotationOfAllTargets: true
	threshold: 4, 4
	thresholdType: LessThan, GreaterThan
    annotation: 🍺,　🍷
    startWeekOn: 'Mon'
    color: green
    headerMonthColor: orange
    dimNotInMonth: false
```
<img width="357" height="323" alt="Image" src="https://github.com/user-attachments/assets/ccfa6240-ad03-471e-a58c-365f721027d5" />
