### ISSUE TITLE
Support relative month in initMonth for calendar view

### ISSUE THREAD

**Issue by wenlzhang** [pyrochlore/obsidian-tracker#65]
Is it possible to support relative month in initMonth for calendar view like what one can do for startDate? This way, one can easily focus on the current month.

Or, is there a feasible workaround for now, to always focus on the current month?

**Comment by pyrochlore** [comment]
It's doable.
Currently, if you do not provide initMonth, Tracker will use the month of 'today' in your system.

**Comment by wenlzhang** [comment]
I found the following description regarding this parameter. Maybe it's from a very early version of the documentation.
| `initMonth` | Initial month to show (YYYY-MM) | 1 | last month found |

In my case, if I do not use initMonth, the default month would be a much later month, instead of the current month. For instance, with the following query:
```
searchType: task.done, task.notdone
searchTarget: '.*, .*'
datasetName: Done, Not Done
month:
    color: tomato
    headerMonthColor: orange
    todayRingColor: orange
    selectedRingColor: steelblue
    showSelectedValue: false
```
